### ISSUE TITLE
Implementar função que atualiza atributo em Database

### ISSUE THREAD

**Issue by pserey** [pserey/parktech#17]
Precisa de uma função que atualize um atributo de um objeto no banco de dados, as duas implementações possíveis são:
- Construir um novo objeto, apagar a linha do objeto no banco de dados e fazer um `append` do `show objeto` no final do bd
- **Editar** a string do banco de dados, apagar a linha do objeto no banco de dados e fazer um `append` do `show objeto` no final do bd

Aparentemente, de qualquer maneira, a implementação vai exigir a **deleção** de uma linha do bd, que deve também ser implementada.

**Comment by pserey** [comment]
Remoção de linha pode funcionar da seguinte maneira:
```haskell
linhas <- readArquivo "arquivo.txt"
novasLinhas = remove linhas i -- abstração para remover elemento da lista
stringNovasLinhas = toStringLinhas novasLinhas -- transforma lista de linhas em string separando elementos por \n
writeFile "arquivo.txt" stringNovasLinhas
```

**Comment by lorennavictoria** [comment]
é uma função pra escrever no bd, que é o que ja ta em processo
